FROM node:14

WORKDIR /app

COPY package*.json .

RUN npm install

ENV TZ=Europe/Minsk
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

COPY server.js .
COPY routes/ ./routes
