version: "3.7"

services:
    app:
        image: coursework2
        command: "node server.js"
        working_dir: /app
        ports:
            - 8089:8089
        volumes:
            - ./pub:/app/pub
