FROM nginx:1.20

RUN apt-get update && \
    apt-get install -y nano && \
    rm -rf /var/lib/apt/lists/*

COPY nginx.conf /etc/nginx/

RUN mv /etc/nginx/conf.d/default.conf /etc/nginx/conf.d/default.conf.old
